const textStories = [
    { name: "Brijal Savaliya", country: "Canada", visa: "Work Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Geetaben D. Patel", country: "Canada", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Sriyam Savaliya", country: "Canada", visa: "Student Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Soni Shanikumar", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Vidhi S. Soni", country: "New Zealand", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Divy S. Soni", country: "New Zealand", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Sunny Prajapati", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Gambhir Singh", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Dhruvkumar Patel", country: "UK", visa: "Student Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Foram Patel", country: "UK", visa: "Work Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Meenaben Savaliya", country: "Canada", visa: "Work Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Sanjay Patel", country: "UK", visa: "Work Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Dipen Patel", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Hansaben Patel", country: "UK", visa: "Visitor Visa (10 Year)", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Parthkumar Patel", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Rameshbhai Patel", country: "UK", visa: "Visitor Visa (10 Year)", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Sagarkumar Patel", country: "Spain", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/es.png" },
    { name: "Sweta Patel", country: "UK", visa: "Work Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Hardikkumar Viradiya", country: "Singapore", visa: "Student Visa", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Riya Rupareliya", country: "Singapore", visa: "Student Visa", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Parth Chothani", country: "Singapore", visa: "Student Visa", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Vijay Panchal", country: "Singapore", visa: "Student Visa", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Parth Akhaja", country: "Singapore", visa: "Student Visa", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Nikunjbhai Patel", country: "Mauritius", visa: "Student Visa", flag: "https://flagcdn.com/w320/mu.png" },
    { name: "Rahul Patel", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Kiritbhai Jogani", country: "UK", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Parulben Jogani", country: "UK", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Payal Patel", country: "UK", visa: "Work Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Jay Sorathiya", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Bhavesh Desai", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Hiren Dhaduk", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Kiya Desai", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Krima Patel", country: "UK", visa: "Dependent Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Luckykumari Jadeja", country: "UK", visa: "Work Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Shivani Patel", country: "New Zealand", visa: "Dependent Visitor Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Dharmeshbhai Patel", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Akshar J. Desai", country: "UK", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Geetaben P. Patel", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Pareshkumar D. Dobaria", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Akash Desai", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Prashantkumar M. Patel", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Suraj P. Dobaria", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Dipakkumar K. Bhesania", country: "Canada", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Rekhaben D. Bhesania", country: "Canada", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Renishkumar A. Patel", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Jietendrasinh Sodha", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Jitendrasingh", country: "UK", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Bhavesh D. Hapani", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Sanju Panwar", country: "UK", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "Bhargav P. Gorasiya", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Nikhar Hirpara", country: "USA", visa: "Student Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Karan Rathod", country: "Italy", visa: "Free Study Visa", flag: "https://flagcdn.com/w320/it.png" },
    { name: "Siddarth Lunagariya", country: "Canada", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Manubhai S. Patel", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Minaben M. Patel", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Arpan V. Patel", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Dhavalkumar B. Desai", country: "New Zealand", visa: "Work Visa", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Kaushl J. Panchal", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Hiteshkumar M. Savaliya", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Manishaben H. Savaliya", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Jashiben Ramesh Desai", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Ishaan Rameshbhai Desai", country: "USA", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/us.png" },
    { name: "Alpaben G. Panchal", country: "Canada", visa: "Visitor Visa", flag: "https://flagcdn.com/w320/ca.png" }
];
